---
- name: Reboot if required - (APT)
  block:

    - name: Check if a reboot is required - (APT)
      register: reboot_required_file
      ansible.builtin.stat: path=/var/run/reboot-required

    - name: Output '/var/run/reboot-required'
      ansible.builtin.debug:
        msg: "{{ reboot_required_file }}"

    - name: Reboot server - (APT)
      ansible.builtin.reboot:
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists

  when: ansible_facts['os_family'] == "Debian"